import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Image from 'next/image';
import { MagnifyingGlassIcon, MicrophoneIcon } from '@heroicons/react/24/solid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <form className='flex flex-col items-center mt-40'>
        <Image
          src={'/google-logo-full.png'}
          alt={'Google logo'}
          width={272}
          height={92}
        />

        <div className='flex w-full justify-center mt-5 mx-auto max-w-[700px] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full sm:max-w-xl lg:max-w-2xl'>
          <MagnifyingGlassIcon className='h-5 text-gray-500 mr-3' />
          <input type='text' className='flex-grow focus:outline-none' />
          <MicrophoneIcon className='h-5' />
        </div>
        <div className='flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center'>
          <button className='btn'>Google Search</button>
          <button className='btn'>I'm Feeling Lucky</button>
        </div>
      </form>
    </div>
  );
}
